name: Publish Chrome Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          zip -r chrome-extension.zip . -x "*.git*" -x "*.DS_Store" -x "node_modules/*"

      - name: Publish to Chrome Web Store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ${{ secrets.EXTENSION_ID }}
          zip: chrome-extension.zip
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

      - name: Clean up
        if: always()
        run: |
          rm -f chrome-extension.zip
          echo "Cleaned up temporary files" 